definitions:
  request.DeploymentRequest:
    properties:
      namespace:
        type: string
      object:
        additionalProperties: true
        type: object
    type: object
  request.PodRequest:
    properties:
      containerName:
        type: string
      containerPort:
        type: integer
      image:
        type: string
      labels:
        additionalProperties:
          type: string
        type: object
      namespace:
        type: string
      podName:
        type: string
    type: object
  response.CommonResponse:
    properties:
      response message: {}
    type: object
info:
  contact: {}
  description: This is a k8s cluster management service
  title: K8S Client API
  version: 0.0.1
paths:
  /pod/createDeployment:
    post:
      parameters:
      - description: Deployment simple configuration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.DeploymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 创建 Deployment
      tags:
      - Deployment
  /pod/createPod:
    post:
      parameters:
      - description: Pod simple configuration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.PodRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 创建 Pod
      tags:
      - Pod
  /pod/deleteDeployment:
    post:
      parameters:
      - default: default
        description: 命名空间
        in: query
        name: namespace
        type: string
      - description: deployment 名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 删除单个 Deployment
      tags:
      - Deployment
  /pod/deletePod:
    post:
      parameters:
      - default: default
        description: 命名空间
        in: query
        name: namespace
        type: string
      - description: pod名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 删除单个 Pod
      tags:
      - Pod
  /pod/getPod:
    post:
      parameters:
      - default: default
        description: 命名空间
        in: query
        name: namespace
        type: string
      - description: pod名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 获取单个 Pod 信息
      tags:
      - Pod
  /pod/listAllPod:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 获取所有 Pod 信息
      tags:
      - Pod
  /pod/listNamespacePod/{namespace}:
    get:
      parameters:
      - default: default
        description: 命名空间
        in: path
        name: namespace
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 获取单个命名空间中所有的  Pod 信息
      tags:
      - Pod
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
